spring.application.name=cache

server.port=8056


    spring.datasource.url=jdbc:postgresql://localhost:5432/cachePrac
    spring.datasource.username=postgres
    spring.datasource.password=Shakti
    # spring.datasource.password=ishan!1
    # spring.datasource.password=Sulav_1552
    spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update


# redis setup
    spring.redis.host=localhost
    spring.redis.port=6379

    # Enable caching
spring.cache.type=redis
